parameters:
    env(MAILER_ENCRYPTION): null
    database_host: "%env(DB_HOST)%"
    database_port: "%env(DB_PORT)%"
    database_name: "%env(DB_NAME)%"
    database_user: "%env(DB_USER)%"
    database_password: "%env(DB_PASSWORD)%"
    mailer_transport: "%env(MAILER_TRANSPORT)%"
    mailer_host: "%env(MAILER_HOST)%"
    mailer_user: "%env(MAILER_USER)%"
    mailer_password: "%env(MAILER_PASSWORD)%"
    mailer_sender: "%env(MAILER_SENDER)%"
    mailer_port: "%env(MAILER_PORT)%"
    mailer_encryption: "%env(MAILER_ENCRYPTION)%"
    secret: $DB_SECRET
    default_network: "%env(DEFAULT_NETWORK)%"
    team_mail: "%env(TEAM_MAIL)%"
    team_abuse: "%env(TEAM_ABUSE)%"
    team_url: "%env(TEAM_URL)%"
    team_name: "%env(TEAM_NAME)%"
    team_site: "%env(TEAM_SITE)%"
    team_logo: "%env(TEAM_LOGO)%"
    ngen_sign: "%env(NGEN_SIGN)%"
    ngen_lang: "%env(NGEN_LANG)%"
    session_max_idle_time: "%env(SESSION_TIMEOUT)%"
    elastic_host: "%env(ELASTIC_HOST)%"
    elastic_port: "%env(ELASTIC_PORT)%"
    # Options {localhost:993/imap/ssl/novalidate-cert}INBOX {localhost:143}INBOX
    imap_server: "%env(IMAP_SERVER)%"
    imap_username: "%env(IMAP_USERNAME)%"
    imap_password: "%env(IMAP_PASSWORD)%"
    external_dashboard_grafana: "%env(EXTERNAL_DASHBOARD_GRAFANA)%"
    internal_dashboard_grafana: "%env(INTERNAL_DASHBOARD_GRAFANA)%"
