# This file is part of the Ngen - CSIRT Incident Report System.
# 
# (c) CERT UNLP <support@cert.unlp.edu.ar>
# 
# This source file is subject to the GPL v3.0 license that is bundled
# with this source code in the file LICENSE.

cert_ngen:
    team:
        mail:

    indcidents:
        internal:
            class: CertUnlp\NgenBundle\Entity\Incident\InternalIncident
            handler:
                class: CertUnlp\NgenBundle\Services\Api\Handler\InternalIncidentHandler
            delegator_chain:
                class: CertUnlp\NgenBundle\Services\Delegator\InternalIncidentDelegatorChain
            form_type:
                class: CertUnlp\NgenBundle\Form\InternalIncidentType
            reports:
                markdown:
                    path: %kernel.root_dir%/../src/CertUnlp/NgenBundle/Resources/views/InternalIncident/Report/Markdown
                twig:
                    path: %kernel.root_dir%/../src/CertUnlp/NgenBundle/Resources/views/InternalIncident/Report/Twig
            mailer:
                class: CertUnlp\NgenBundle\Services\Mailer\InternalIncidentMailer

        external:
            class: CertUnlp\NgenBundle\Entity\Incident\ExternalIncident
            handler:
                class: CertUnlp\NgenBundle\Services\Api\Handler\ExternalIncidentHandler
            delegator_chain:
                class: CertUnlp\NgenBundle\Services\Delegator\ExternalIncidentDelegatorChain
            form_type:
                class: CertUnlp\NgenBundle\Form\ExternalIncidentType
            reports:
                markdown:
                    path: %kernel.root_dir%/../src/CertUnlp/NgenBundle/Resources/views/ExternalIncident/Report/Markdown
                twig:
                    path: %kernel.root_dir%/../src/CertUnlp/NgenBundle/Resources/views/ExternalIncident/Report/Twig
            mailer:
                class: CertUnlp\NgenBundle\Services\Mailer\ExternalIncidentMailer

        mailer:
            class: CertUnlp\NgenBundle\Services\IncidentMailer
            transport: smtp
            host: ~
            username: ~
            password: ~
            sender_address: ~
        evidence:
            path: %kernel.root_dir%/Resources/incident/evidence #pasar a external internal
            prefix: ~
        factory:
            class: CertUnlp\NgenBundle\Services\IncidentFactory

        reporter:
            class: CertUnlp\NgenBundle\Entity\User
                feeds:
            class: CertUnlp\NgenBundle\Entity\Incident\IncidentFeed
            handler:
                class: CertUnlp\NgenBundle\Services\Api\Handler\IncidentFeedHandler
            form_type:
                class: CertUnlp\NgenBundle\Form\IncidentFeedType

        states:
            class: CertUnlp\NgenBundle\Entity\Incident\IncidentState
            handler:
                class: CertUnlp\NgenBundle\Services\Api\Handler\IncidentStateHandler
            form_type:
                class: CertUnlp\NgenBundle\Form\IncidentStateType

        types:
            class: CertUnlp\NgenBundle\Entity\Incident\IncidentType
            handler:
                class: CertUnlp\NgenBundle\Services\Api\Handler\IncidentTypeHandler
            form_type:
                class: CertUnlp\NgenBundle\Form\IncidentTypeType

    networks:
        class: CertUnlp\NgenBundle\Entity\Network\Network
        default_network: ~
        handler:
            class: CertUnlp\NgenBundle\Services\Api\Handler\NetworkHandler
        validator:
            class: CertUnlp\NgenBundle\Validator\Constraints\ValidNetworkValidator
        form_type:
            class: CertUnlp\NgenBundle\Form\NetworkType
        admin:
            class: CertUnlp\NgenBundle\Entity\Network\NetworkAdmin
            handler:
                class: CertUnlp\NgenBundle\Services\Api\Handler\NetworkAdminHandler
            form_type:
                class: CertUnlp\NgenBundle\Form\NetworkAdminType

    users:
        class: CertUnlp\NgenBundle\Entity\User
        handler:
            class: CertUnlp\NgenBundle\Services\Api\Handler\UserHandler
        form_type:
            class: CertUnlp\NgenBundle\Form\UserType

    feeds:
        path: %kernel.root_dir%/Resources/feed
        shadowserver:
            class: CertUnlp\NgenBundle\Services\ShadowServer\ShadowServerAnalyzer
            client:
                class: CertUnlp\NgenBundle\Services\ShadowServer\ShadowServerClient
                url: https://dl.shadowserver.org/reports/index.php
                user: ~
                password: ~
    seeds:
        redmine:
            class: CertUnlp\NgenBundle\Services\IncidentRedmine
            url: ~
            key: ~

               