# This file is part of the Ngen - CSIRT Incident Report System.
#
# (c) CERT UNLP <support@cert.unlp.edu.ar>
#
# This source file is subject to the GPL v3.0 license that is bundled
# with this source code in the file LICENSE.

cert_ngen_user:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserFrontendController.php'
    type:     annotation
    prefix:   /users

cert_ngen_user_security:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserSecurityFrontendController.php'
    type:     annotation
    prefix:   /users

cert_ngen_user_resetting:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserResettingFrontendController.php'
    type:     annotation
    prefix:   /users/resetting

cert_ngen_user_registration:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserRegistrationFrontendController.php'
    type:     annotation
    prefix:   /users/register

cert_ngen_user_profile:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserProfileFrontendController.php'
    type:     annotation
    prefix:   /users/profile

cert_ngen_user_change_password:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/User/UserChangePasswordFrontendController.php'
    type:     annotation
    prefix:   /users/profile

cert_ngen_network_entity:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Constituency/NetworkEntityFrontendController.php'
    type:     annotation
    prefix:   /contituency/entities

cert_ngen_network_admin:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Constituency/NetworkAdminFrontendController.php'
    type:     annotation
    prefix:   /contituency/admins

cert_ngen_network:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Constituency/NetworkElement/NetworkFrontendController.php'
    type:     annotation
    prefix:   /contituency/networks

cert_ngen_host:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Constituency/NetworkElement/HostFrontendController.php'
    type:   annotation
    prefix:    /contituency/hosts

cert_ngen_internal_incident:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentFrontendController.php'
    type:   annotation
    prefix:   /incidents

cert_ngen_administration_feed:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentFeedFrontendController.php'
    type:     annotation
    prefix:   /administration/feeds

cert_ngen_administration_state:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentStateFrontendController.php'
    type:     annotation
    prefix:   /administration/states

cert_ngen_administration_type:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentTypeFrontendController.php'
    type:     annotation
    prefix:   /administration/types

cert_ngen_administration_decision:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentDecisionFrontendController.php'
    type:     annotation
    prefix:   /administration/decisions

cert_ngen_administration_priority:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentPriorityFrontendController.php'
    type:     annotation
    prefix:   /administration/priorities

cert_ngen_administration_taxonomy_values:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentTaxonomyValueFrontendController.php'
    type:     annotation
    prefix:   /administration/taxonomies/values

cert_ngen_administration_taxonomy_predicates:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentTaxonomyPredicateFrontendController.php'
    type:     annotation
    prefix:   /administration/taxonomies/predicates

cert_ngen_incident_detected:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentDetectedFrontendController.php'
    type:   annotation
    prefix:   /incidents_detected


cert_ngen_administration_type_reports:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentReportFrontendController.php'
    type:     annotation
    prefix:   /incidents/types

cert_ngen_root:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/Incident/IncidentFrontendController.php'
    type:     annotation
    prefix:   /

#fos_comment_api:
#    type: rest
#    resource: '@FOSCommentBundle/Resources/config/routing.yml'
#    defaults: { _format: html }

cert_ngen_dashboard:
    resource: '@CertUnlpNgenBundle/Controller/Frontend/DashboardController.php'
    type:     annotation
    prefix:   /dashboard

cert_ngen_api:
    type: rest
    prefix: /api
    resource: '@CertUnlpNgenBundle/Resources/config/routing_api.yml'

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
