# This file is part of the Ngen - CSIRT Incident Report System.
# 
# (c) CERT UNLP <support@cert.unlp.edu.ar>
# 
# This source file is subject to the GPL v3.0 license that is bundled
# with this source code in the file LICENSE.

#_welcome:
#    path:      /
#    defaults:  { _controller: CertUnlpNgenBundle:Default:home }

cert_ngen_user:
    resource: '@CertUnlpNgenBundle/Controller/UserFrontendController.php'
    type:     annotation
    prefix:   /user
    
cert_ngen_network_admin:
    resource: '@CertUnlpNgenBundle/Controller/NetworkAdminFrontendController.php'
    type:     annotation
    prefix:   /networks/admins
    
cert_ngen_network:
    resource: '@CertUnlpNgenBundle/Controller/NetworkFrontendController.php'
    type:     annotation
    prefix:   /networks    
    
cert_ngen_internal_incident:
    resource: '@CertUnlpNgenBundle/Controller/InternalIncidentFrontendController.php'
    type:     annotation
    prefix:   /incidents/internals
    
cert_ngen_external_incident:
    resource: '@CertUnlpNgenBundle/Controller/ExternalIncidentFrontendController.php'
    type:     annotation
    prefix:   /incidents/externals

cert_ngen_incident_feed:
    resource: '@CertUnlpNgenBundle/Controller/IncidentFeedFrontendController.php'
    type:     annotation
    prefix:   /incidents/feeds

cert_ngen_incident_state:
    resource: '@CertUnlpNgenBundle/Controller/IncidentStateFrontendController.php'
    type:     annotation
    prefix:   /incidents/states

cert_ngen_incident_type:
    resource: '@CertUnlpNgenBundle/Controller/IncidentTypeFrontendController.php'
    type:     annotation
    prefix:   /incidents/types
    
cert_ngen_dashboard:
    resource: '@CertUnlpNgenBundle/Controller/DashboardController.php'
    type:     annotation
#    prefix:   /incidents/types
    
fos_comment_api:
    type: rest
    resource: '@FOSCommentBundle/Resources/config/routing.yml'
    defaults: { _format: html }

cert_ngen_api:
    type: rest
    prefix: /api
    resource: '@CertUnlpNgenBundle/Resources/config/routing_api.yml'

NelmioApiDocBundle:
    resource: '@NelmioApiDocBundle/Resources/config/routing.yml'
    prefix:   /incidents/api/doc