version: "3.1"
volumes:
  ngen-grafana-data:
    driver: local
    #driver: rancher-nfs
    #external: true 
  ngen-elastic-data:
    driver: local
    #driver: rancher-nfs
    #external: true
  ngen-elasticsearch:
    driver: local
    #driver: rancher-nfs
    #external: true
  ngen-bdd:
    driver: local
    #driver: rancher-nfs
    #external: true
  ngen-incidentes:
    driver: local
    #driver: rancher-nfs
    #external: true
  ngen-feeds:
    driver: local
    #driver: rancher-nfs
    #external: true
services:
    ngen-db:
      image: mysql:5.7
      volumes:
        - ngen-bdd:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=ngen
        - MYSQL_USER=ngenuser
        - MYSQL_PASSWORD=ngenpass
      ports:
        - "8002:3306"
      networks: ['ngen']
    ngen-app:
      image: einar1/ngen:0.6.6
      networks: ['ngen']
      depends_on: ['ngen-db','ngen-elastic']
      ports:
        - "8000:80"
      volumes:
        - '../:/application/ngen_basic/vendor/certunlp/ngen-bundle/'
        - ngen-incidentes:/application/ngen_basic/app/Resources/incident
        - ngen-feeds:/application/ngen_basic/app/Resources/app/Resources/feed/
      environment:
        - PATH_WEB=/application
        #Secret key (Si no tienes una, dejarla vacía, el instalador creará una):
        - DATE_TZ=America/Argentina/Buenos_Aires
        - MEMORY_LIMIT=1024M
        - POST_MAX=20M
        - UPLOAD_MAX=20M
        - DB_HOST=ngen-db
        - DB_PORT=3306
        - DB_NAME=ngen
        - DB_USER=ngenuser
        - DB_PASSWORD=ngenpass
        - MAILER_TRANSPORT=smtp
        - MAILER_PORT=587
        - MAILER_HOST=mail-app.info.unlp.edu.ar
        - MAILER_USER=null
        - MAILER_PASSWORD=null
        - MAILER_SENDER=pepe@localhost
        - TEAM_MAIL=pepe@localhost 
        - DEFAULT_NETWORK=10.0.0.0
        - ELASTIC_HOST=ngen-elastic
        - ELASTIC_PORT=9200
        - SESSION_TIMEOUT=1800
      links:
        - ngen-elastic:ngen-elastic
        - ngen-db:ngen-db
    ngen-elastic:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
      environment:
       - cluster.name=docker-cluster
       - discovery.type=single-node
       - xpack.security.enabled=false
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      volumes:
        - ngen-elastic-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      networks: ['ngen']
    ngen-grafana:
      image: einar1/ngen-grafana:0.1
      ports:
        - "3000:3000"
      volumes:
        - ngen-grafana-data:/var/lib/grafana
      environment:
        - ELASTIC_HOST=ngen-elastic
        - ELASTIC_PORT=9200
      networks: ['ngen']
      depends_on: ['ngen-elastic']
      links:
          - ngen-elastic:ngen-elastic

networks: {ngen: {}}
